version: '3'
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db-v:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - intra

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - ADMIN_USER=${MYSQL_USER}
      - ADMIN_PASSWORD=${MYSQL_PASSWORD}
      - USER_ID=${USER_ID}
      - USER_PASSWORD=${USER_PWD}
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - www-v:/var/www
    networks:
      - intra

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - www-v:/var/www
    depends_on:
      - wordpress
    networks:
      - intra

volumes:
    db-v:
        name: db-v
        driver: local
        driver_opts:
            device: '/Users/donghakl/data/db'
            type: 'none'
            o: 'bind'

    www-v:
        name: www-v
        driver: local
        driver_opts:
            device: '/Users/donghakl/data/wordpress'
            type: 'none'
            o: 'bind'

networks:
    intra:
        driver: bridge
