version: '3'
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db-v:/var/lib/mysql
    env_file:
      - .env
    networks:
      - intra

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - www-v:/var/www
    networks:
      - intra

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - www-v:/var/www
    depends_on:
      - wordpress
    networks:
      - intra

volumes:
    db-v:
        name: db-v
        driver: local
        driver_opts:
            device: '/home/donghakl/data/db'
            type: 'none'
            o: 'bind'

    www-v:
        name: www-v
        driver: local
        driver_opts:
            device: '/home/donghakl/data/wordpress'
            type: 'none'
            o: 'bind'

networks:
    intra:
        driver: bridge
